// Generated by gencpp from file coffebot/Audio.msg
// DO NOT EDIT!


#ifndef COFFEBOT_MESSAGE_AUDIO_H
#define COFFEBOT_MESSAGE_AUDIO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coffebot
{
template <class ContainerAllocator>
struct Audio_
{
  typedef Audio_<ContainerAllocator> Type;

  Audio_()
    : content()  {
    }
  Audio_(const ContainerAllocator& _alloc)
    : content(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _content_type;
  _content_type content;




  typedef boost::shared_ptr< ::coffebot::Audio_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coffebot::Audio_<ContainerAllocator> const> ConstPtr;

}; // struct Audio_

typedef ::coffebot::Audio_<std::allocator<void> > Audio;

typedef boost::shared_ptr< ::coffebot::Audio > AudioPtr;
typedef boost::shared_ptr< ::coffebot::Audio const> AudioConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coffebot::Audio_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coffebot::Audio_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coffebot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'coffebot': ['/home/alex/catkin_ws/src/coffebot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::Audio_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::Audio_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::Audio_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::Audio_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::Audio_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::Audio_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coffebot::Audio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72abf3d8306e84a4caf970654ef2815d";
  }

  static const char* value(const ::coffebot::Audio_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72abf3d8306e84a4ULL;
  static const uint64_t static_value2 = 0xcaf970654ef2815dULL;
};

template<class ContainerAllocator>
struct DataType< ::coffebot::Audio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coffebot/Audio";
  }

  static const char* value(const ::coffebot::Audio_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coffebot::Audio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] content\n\
";
  }

  static const char* value(const ::coffebot::Audio_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coffebot::Audio_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.content);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Audio_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coffebot::Audio_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coffebot::Audio_<ContainerAllocator>& v)
  {
    s << indent << "content[]" << std::endl;
    for (size_t i = 0; i < v.content.size(); ++i)
    {
      s << indent << "  content[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.content[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COFFEBOT_MESSAGE_AUDIO_H
