// Generated by gencpp from file coffebot/EyesMotion.msg
// DO NOT EDIT!


#ifndef COFFEBOT_MESSAGE_EYESMOTION_H
#define COFFEBOT_MESSAGE_EYESMOTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coffebot
{
template <class ContainerAllocator>
struct EyesMotion_
{
  typedef EyesMotion_<ContainerAllocator> Type;

  EyesMotion_()
    : angle(0.0)
    , distance_from_center_percent(0.0)
    , emotion()  {
    }
  EyesMotion_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , distance_from_center_percent(0.0)
    , emotion(_alloc)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;

   typedef float _distance_from_center_percent_type;
  _distance_from_center_percent_type distance_from_center_percent;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _emotion_type;
  _emotion_type emotion;




  typedef boost::shared_ptr< ::coffebot::EyesMotion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coffebot::EyesMotion_<ContainerAllocator> const> ConstPtr;

}; // struct EyesMotion_

typedef ::coffebot::EyesMotion_<std::allocator<void> > EyesMotion;

typedef boost::shared_ptr< ::coffebot::EyesMotion > EyesMotionPtr;
typedef boost::shared_ptr< ::coffebot::EyesMotion const> EyesMotionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coffebot::EyesMotion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coffebot::EyesMotion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coffebot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'coffebot': ['/home/alex/catkin_ws/src/coffebot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::EyesMotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::EyesMotion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::EyesMotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::EyesMotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::EyesMotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::EyesMotion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coffebot::EyesMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a9c274e737c0b917a24ecaa2a12792e";
  }

  static const char* value(const ::coffebot::EyesMotion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a9c274e737c0b91ULL;
  static const uint64_t static_value2 = 0x7a24ecaa2a12792eULL;
};

template<class ContainerAllocator>
struct DataType< ::coffebot::EyesMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coffebot/EyesMotion";
  }

  static const char* value(const ::coffebot::EyesMotion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coffebot::EyesMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n\
float32 distance_from_center_percent\n\
string emotion\n\
";
  }

  static const char* value(const ::coffebot::EyesMotion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coffebot::EyesMotion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.distance_from_center_percent);
      stream.next(m.emotion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct EyesMotion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coffebot::EyesMotion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coffebot::EyesMotion_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "distance_from_center_percent: ";
    Printer<float>::stream(s, indent + "  ", v.distance_from_center_percent);
    s << indent << "emotion: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.emotion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COFFEBOT_MESSAGE_EYESMOTION_H
