// Generated by gencpp from file coffebot/HeadMotion.msg
// DO NOT EDIT!


#ifndef COFFEBOT_MESSAGE_HEADMOTION_H
#define COFFEBOT_MESSAGE_HEADMOTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coffebot
{
template <class ContainerAllocator>
struct HeadMotion_
{
  typedef HeadMotion_<ContainerAllocator> Type;

  HeadMotion_()
    : h_angle(0.0)
    , v_angle(0.0)
    , emotion()  {
    }
  HeadMotion_(const ContainerAllocator& _alloc)
    : h_angle(0.0)
    , v_angle(0.0)
    , emotion(_alloc)  {
  (void)_alloc;
    }



   typedef float _h_angle_type;
  _h_angle_type h_angle;

   typedef float _v_angle_type;
  _v_angle_type v_angle;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _emotion_type;
  _emotion_type emotion;




  typedef boost::shared_ptr< ::coffebot::HeadMotion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coffebot::HeadMotion_<ContainerAllocator> const> ConstPtr;

}; // struct HeadMotion_

typedef ::coffebot::HeadMotion_<std::allocator<void> > HeadMotion;

typedef boost::shared_ptr< ::coffebot::HeadMotion > HeadMotionPtr;
typedef boost::shared_ptr< ::coffebot::HeadMotion const> HeadMotionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coffebot::HeadMotion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coffebot::HeadMotion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coffebot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'coffebot': ['/home/alex/catkin_ws/src/coffebot/msg', '/home/alex/catkin_ws/devel/share/coffebot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::HeadMotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::HeadMotion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::HeadMotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::HeadMotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::HeadMotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::HeadMotion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coffebot::HeadMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57dac4b62b684f84f46d1dd244edf1e0";
  }

  static const char* value(const ::coffebot::HeadMotion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57dac4b62b684f84ULL;
  static const uint64_t static_value2 = 0xf46d1dd244edf1e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::coffebot::HeadMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coffebot/HeadMotion";
  }

  static const char* value(const ::coffebot::HeadMotion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coffebot::HeadMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 h_angle # 0.0 <= h_angle <= 360.0\n\
float32 v_angle # 0.0 <= v_angle <= 360.0\n\
string emotion\n\
";
  }

  static const char* value(const ::coffebot::HeadMotion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coffebot::HeadMotion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.h_angle);
      stream.next(m.v_angle);
      stream.next(m.emotion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct HeadMotion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coffebot::HeadMotion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coffebot::HeadMotion_<ContainerAllocator>& v)
  {
    s << indent << "h_angle: ";
    Printer<float>::stream(s, indent + "  ", v.h_angle);
    s << indent << "v_angle: ";
    Printer<float>::stream(s, indent + "  ", v.v_angle);
    s << indent << "emotion: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.emotion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COFFEBOT_MESSAGE_HEADMOTION_H
