// Generated by gencpp from file coffebot/MakeVideoGoal.msg
// DO NOT EDIT!


#ifndef COFFEBOT_MESSAGE_MAKEVIDEOGOAL_H
#define COFFEBOT_MESSAGE_MAKEVIDEOGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <coffebot/MakeVideo.h>

namespace coffebot
{
template <class ContainerAllocator>
struct MakeVideoGoal_
{
  typedef MakeVideoGoal_<ContainerAllocator> Type;

  MakeVideoGoal_()
    : make_photo_command()  {
    }
  MakeVideoGoal_(const ContainerAllocator& _alloc)
    : make_photo_command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::coffebot::MakeVideo_<ContainerAllocator>  _make_photo_command_type;
  _make_photo_command_type make_photo_command;




  typedef boost::shared_ptr< ::coffebot::MakeVideoGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coffebot::MakeVideoGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MakeVideoGoal_

typedef ::coffebot::MakeVideoGoal_<std::allocator<void> > MakeVideoGoal;

typedef boost::shared_ptr< ::coffebot::MakeVideoGoal > MakeVideoGoalPtr;
typedef boost::shared_ptr< ::coffebot::MakeVideoGoal const> MakeVideoGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coffebot::MakeVideoGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coffebot::MakeVideoGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coffebot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'coffebot': ['/home/alex/catkin_ws/src/coffebot/msg', '/home/alex/catkin_ws/devel/share/coffebot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::MakeVideoGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::MakeVideoGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::MakeVideoGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::MakeVideoGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::MakeVideoGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::MakeVideoGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coffebot::MakeVideoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e36709e19038e609a732049e64a6b96";
  }

  static const char* value(const ::coffebot::MakeVideoGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e36709e19038e60ULL;
  static const uint64_t static_value2 = 0x9a732049e64a6b96ULL;
};

template<class ContainerAllocator>
struct DataType< ::coffebot::MakeVideoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coffebot/MakeVideoGoal";
  }

  static const char* value(const ::coffebot::MakeVideoGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coffebot::MakeVideoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
MakeVideo make_photo_command\n\
\n\
================================================================================\n\
MSG: coffebot/MakeVideo\n\
#message for command to make video\n\
\n\
bool start_video\n\
int8 duration #duration in seconds\n\
string video_file_name\n\
";
  }

  static const char* value(const ::coffebot::MakeVideoGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coffebot::MakeVideoGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.make_photo_command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MakeVideoGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coffebot::MakeVideoGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coffebot::MakeVideoGoal_<ContainerAllocator>& v)
  {
    s << indent << "make_photo_command: ";
    s << std::endl;
    Printer< ::coffebot::MakeVideo_<ContainerAllocator> >::stream(s, indent + "  ", v.make_photo_command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COFFEBOT_MESSAGE_MAKEVIDEOGOAL_H
