// Generated by gencpp from file coffebot/MakePhoto.msg
// DO NOT EDIT!


#ifndef COFFEBOT_MESSAGE_MAKEPHOTO_H
#define COFFEBOT_MESSAGE_MAKEPHOTO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coffebot
{
template <class ContainerAllocator>
struct MakePhoto_
{
  typedef MakePhoto_<ContainerAllocator> Type;

  MakePhoto_()
    : make_photo(false)
    , photo_file_name()  {
    }
  MakePhoto_(const ContainerAllocator& _alloc)
    : make_photo(false)
    , photo_file_name(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _make_photo_type;
  _make_photo_type make_photo;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _photo_file_name_type;
  _photo_file_name_type photo_file_name;




  typedef boost::shared_ptr< ::coffebot::MakePhoto_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coffebot::MakePhoto_<ContainerAllocator> const> ConstPtr;

}; // struct MakePhoto_

typedef ::coffebot::MakePhoto_<std::allocator<void> > MakePhoto;

typedef boost::shared_ptr< ::coffebot::MakePhoto > MakePhotoPtr;
typedef boost::shared_ptr< ::coffebot::MakePhoto const> MakePhotoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coffebot::MakePhoto_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coffebot::MakePhoto_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coffebot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'coffebot': ['/home/alex/catkin_ws/src/coffebot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::MakePhoto_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::MakePhoto_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::MakePhoto_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::MakePhoto_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::MakePhoto_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::MakePhoto_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coffebot::MakePhoto_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0d1193fa54b08a2d5ae161d953ba3b1";
  }

  static const char* value(const ::coffebot::MakePhoto_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0d1193fa54b08a2ULL;
  static const uint64_t static_value2 = 0xd5ae161d953ba3b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::coffebot::MakePhoto_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coffebot/MakePhoto";
  }

  static const char* value(const ::coffebot::MakePhoto_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coffebot::MakePhoto_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#message for command to make photo\n\
\n\
bool make_photo\n\
string photo_file_name\n\
";
  }

  static const char* value(const ::coffebot::MakePhoto_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coffebot::MakePhoto_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.make_photo);
      stream.next(m.photo_file_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MakePhoto_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coffebot::MakePhoto_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coffebot::MakePhoto_<ContainerAllocator>& v)
  {
    s << indent << "make_photo: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.make_photo);
    s << indent << "photo_file_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.photo_file_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COFFEBOT_MESSAGE_MAKEPHOTO_H
