// Generated by gencpp from file coffebot/MakePhotoGoal.msg
// DO NOT EDIT!


#ifndef COFFEBOT_MESSAGE_MAKEPHOTOGOAL_H
#define COFFEBOT_MESSAGE_MAKEPHOTOGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <coffebot/MakePhoto.h>

namespace coffebot
{
template <class ContainerAllocator>
struct MakePhotoGoal_
{
  typedef MakePhotoGoal_<ContainerAllocator> Type;

  MakePhotoGoal_()
    : make_photo_command()  {
    }
  MakePhotoGoal_(const ContainerAllocator& _alloc)
    : make_photo_command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::coffebot::MakePhoto_<ContainerAllocator>  _make_photo_command_type;
  _make_photo_command_type make_photo_command;




  typedef boost::shared_ptr< ::coffebot::MakePhotoGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coffebot::MakePhotoGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MakePhotoGoal_

typedef ::coffebot::MakePhotoGoal_<std::allocator<void> > MakePhotoGoal;

typedef boost::shared_ptr< ::coffebot::MakePhotoGoal > MakePhotoGoalPtr;
typedef boost::shared_ptr< ::coffebot::MakePhotoGoal const> MakePhotoGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coffebot::MakePhotoGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coffebot::MakePhotoGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coffebot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'coffebot': ['/home/alex/catkin_ws/src/coffebot/msg', '/home/alex/catkin_ws/devel/share/coffebot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::MakePhotoGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::MakePhotoGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::MakePhotoGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::MakePhotoGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::MakePhotoGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::MakePhotoGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coffebot::MakePhotoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00b32418588cddf81e8ce2583c63f170";
  }

  static const char* value(const ::coffebot::MakePhotoGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00b32418588cddf8ULL;
  static const uint64_t static_value2 = 0x1e8ce2583c63f170ULL;
};

template<class ContainerAllocator>
struct DataType< ::coffebot::MakePhotoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coffebot/MakePhotoGoal";
  }

  static const char* value(const ::coffebot::MakePhotoGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coffebot::MakePhotoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
MakePhoto make_photo_command\n\
\n\
================================================================================\n\
MSG: coffebot/MakePhoto\n\
#message for command to make photo\n\
\n\
bool make_photo\n\
string photo_file_name\n\
";
  }

  static const char* value(const ::coffebot::MakePhotoGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coffebot::MakePhotoGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.make_photo_command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MakePhotoGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coffebot::MakePhotoGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coffebot::MakePhotoGoal_<ContainerAllocator>& v)
  {
    s << indent << "make_photo_command: ";
    s << std::endl;
    Printer< ::coffebot::MakePhoto_<ContainerAllocator> >::stream(s, indent + "  ", v.make_photo_command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COFFEBOT_MESSAGE_MAKEPHOTOGOAL_H
