// Generated by gencpp from file coffebot/MakeVideo.msg
// DO NOT EDIT!


#ifndef COFFEBOT_MESSAGE_MAKEVIDEO_H
#define COFFEBOT_MESSAGE_MAKEVIDEO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coffebot
{
template <class ContainerAllocator>
struct MakeVideo_
{
  typedef MakeVideo_<ContainerAllocator> Type;

  MakeVideo_()
    : start_video(false)
    , duration(0)
    , video_file_name()  {
    }
  MakeVideo_(const ContainerAllocator& _alloc)
    : start_video(false)
    , duration(0)
    , video_file_name(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _start_video_type;
  _start_video_type start_video;

   typedef int8_t _duration_type;
  _duration_type duration;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _video_file_name_type;
  _video_file_name_type video_file_name;




  typedef boost::shared_ptr< ::coffebot::MakeVideo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coffebot::MakeVideo_<ContainerAllocator> const> ConstPtr;

}; // struct MakeVideo_

typedef ::coffebot::MakeVideo_<std::allocator<void> > MakeVideo;

typedef boost::shared_ptr< ::coffebot::MakeVideo > MakeVideoPtr;
typedef boost::shared_ptr< ::coffebot::MakeVideo const> MakeVideoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coffebot::MakeVideo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coffebot::MakeVideo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coffebot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'coffebot': ['/home/alex/catkin_ws/src/coffebot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::MakeVideo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coffebot::MakeVideo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::MakeVideo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coffebot::MakeVideo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::MakeVideo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coffebot::MakeVideo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coffebot::MakeVideo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea5c471bcc115e3b226da65d49ceb188";
  }

  static const char* value(const ::coffebot::MakeVideo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea5c471bcc115e3bULL;
  static const uint64_t static_value2 = 0x226da65d49ceb188ULL;
};

template<class ContainerAllocator>
struct DataType< ::coffebot::MakeVideo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coffebot/MakeVideo";
  }

  static const char* value(const ::coffebot::MakeVideo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coffebot::MakeVideo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#message for command to make video\n\
\n\
bool start_video\n\
int8 duration #duration in seconds\n\
string video_file_name\n\
";
  }

  static const char* value(const ::coffebot::MakeVideo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coffebot::MakeVideo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_video);
      stream.next(m.duration);
      stream.next(m.video_file_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MakeVideo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coffebot::MakeVideo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coffebot::MakeVideo_<ContainerAllocator>& v)
  {
    s << indent << "start_video: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_video);
    s << indent << "duration: ";
    Printer<int8_t>::stream(s, indent + "  ", v.duration);
    s << indent << "video_file_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.video_file_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COFFEBOT_MESSAGE_MAKEVIDEO_H
