# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from coffebot/MakeVideoGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import coffebot.msg

class MakeVideoGoal(genpy.Message):
  _md5sum = "fa6b65ac1fe287cb8e878d75616abc7c"
  _type = "coffebot/MakeVideoGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal
MakeVideo make_video_command

================================================================================
MSG: coffebot/MakeVideo
#message for command to make video

bool start_video
int8 duration #duration in seconds
string video_file_name
"""
  __slots__ = ['make_video_command']
  _slot_types = ['coffebot/MakeVideo']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       make_video_command

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MakeVideoGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.make_video_command is None:
        self.make_video_command = coffebot.msg.MakeVideo()
    else:
      self.make_video_command = coffebot.msg.MakeVideo()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Bb().pack(_x.make_video_command.start_video, _x.make_video_command.duration))
      _x = self.make_video_command.video_file_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.make_video_command is None:
        self.make_video_command = coffebot.msg.MakeVideo()
      end = 0
      _x = self
      start = end
      end += 2
      (_x.make_video_command.start_video, _x.make_video_command.duration,) = _get_struct_Bb().unpack(str[start:end])
      self.make_video_command.start_video = bool(self.make_video_command.start_video)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.make_video_command.video_file_name = str[start:end].decode('utf-8')
      else:
        self.make_video_command.video_file_name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Bb().pack(_x.make_video_command.start_video, _x.make_video_command.duration))
      _x = self.make_video_command.video_file_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.make_video_command is None:
        self.make_video_command = coffebot.msg.MakeVideo()
      end = 0
      _x = self
      start = end
      end += 2
      (_x.make_video_command.start_video, _x.make_video_command.duration,) = _get_struct_Bb().unpack(str[start:end])
      self.make_video_command.start_video = bool(self.make_video_command.start_video)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.make_video_command.video_file_name = str[start:end].decode('utf-8')
      else:
        self.make_video_command.video_file_name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bb = None
def _get_struct_Bb():
    global _struct_Bb
    if _struct_Bb is None:
        _struct_Bb = struct.Struct("<Bb")
    return _struct_Bb
