(cl:defpackage coffebot-msg
  (:use )
  (:export
   "<APIAIBOTANSWER>"
   "APIAIBOTANSWER"
   "<AUDIO>"
   "AUDIO"
   "<BOTSPEECHTEXT>"
   "BOTSPEECHTEXT"
   "<EMOTION>"
   "EMOTION"
   "<FACECOORDINATES>"
   "FACECOORDINATES"
   "<FACEDETECTED>"
   "FACEDETECTED"
   "<MAKEPHOTO>"
   "MAKEPHOTO"
   "<MAKEVIDEO>"
   "MAKEVIDEO"
   "<MOTIONPATTERN>"
   "MOTIONPATTERN"
   "<SMILEDETECTED>"
   "SMILEDETECTED"
   "<USERSPEECHTEXT>"
   "USERSPEECHTEXT"
  ))

