; Auto-generated. Do not edit!


(cl:in-package coffebot-msg)


;//! \htmlinclude MakeVideoGoal.msg.html

(cl:defclass <MakeVideoGoal> (roslisp-msg-protocol:ros-message)
  ((make_photo_command
    :reader make_photo_command
    :initarg :make_photo_command
    :type coffebot-msg:MakeVideo
    :initform (cl:make-instance 'coffebot-msg:MakeVideo)))
)

(cl:defclass MakeVideoGoal (<MakeVideoGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MakeVideoGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MakeVideoGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name coffebot-msg:<MakeVideoGoal> is deprecated: use coffebot-msg:MakeVideoGoal instead.")))

(cl:ensure-generic-function 'make_photo_command-val :lambda-list '(m))
(cl:defmethod make_photo_command-val ((m <MakeVideoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader coffebot-msg:make_photo_command-val is deprecated.  Use coffebot-msg:make_photo_command instead.")
  (make_photo_command m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MakeVideoGoal>) ostream)
  "Serializes a message object of type '<MakeVideoGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'make_photo_command) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MakeVideoGoal>) istream)
  "Deserializes a message object of type '<MakeVideoGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'make_photo_command) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MakeVideoGoal>)))
  "Returns string type for a message object of type '<MakeVideoGoal>"
  "coffebot/MakeVideoGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MakeVideoGoal)))
  "Returns string type for a message object of type 'MakeVideoGoal"
  "coffebot/MakeVideoGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MakeVideoGoal>)))
  "Returns md5sum for a message object of type '<MakeVideoGoal>"
  "6e36709e19038e609a732049e64a6b96")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MakeVideoGoal)))
  "Returns md5sum for a message object of type 'MakeVideoGoal"
  "6e36709e19038e609a732049e64a6b96")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MakeVideoGoal>)))
  "Returns full string definition for message of type '<MakeVideoGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%MakeVideo make_photo_command~%~%================================================================================~%MSG: coffebot/MakeVideo~%#message for command to make video~%~%bool start_video~%int8 duration #duration in seconds~%string video_file_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MakeVideoGoal)))
  "Returns full string definition for message of type 'MakeVideoGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%MakeVideo make_photo_command~%~%================================================================================~%MSG: coffebot/MakeVideo~%#message for command to make video~%~%bool start_video~%int8 duration #duration in seconds~%string video_file_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MakeVideoGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'make_photo_command))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MakeVideoGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MakeVideoGoal
    (cl:cons ':make_photo_command (make_photo_command msg))
))
