; Auto-generated. Do not edit!


(cl:in-package coffebot-msg)


;//! \htmlinclude MakePhotoGoal.msg.html

(cl:defclass <MakePhotoGoal> (roslisp-msg-protocol:ros-message)
  ((make_photo_command
    :reader make_photo_command
    :initarg :make_photo_command
    :type coffebot-msg:MakePhoto
    :initform (cl:make-instance 'coffebot-msg:MakePhoto)))
)

(cl:defclass MakePhotoGoal (<MakePhotoGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MakePhotoGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MakePhotoGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name coffebot-msg:<MakePhotoGoal> is deprecated: use coffebot-msg:MakePhotoGoal instead.")))

(cl:ensure-generic-function 'make_photo_command-val :lambda-list '(m))
(cl:defmethod make_photo_command-val ((m <MakePhotoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader coffebot-msg:make_photo_command-val is deprecated.  Use coffebot-msg:make_photo_command instead.")
  (make_photo_command m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MakePhotoGoal>) ostream)
  "Serializes a message object of type '<MakePhotoGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'make_photo_command) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MakePhotoGoal>) istream)
  "Deserializes a message object of type '<MakePhotoGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'make_photo_command) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MakePhotoGoal>)))
  "Returns string type for a message object of type '<MakePhotoGoal>"
  "coffebot/MakePhotoGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MakePhotoGoal)))
  "Returns string type for a message object of type 'MakePhotoGoal"
  "coffebot/MakePhotoGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MakePhotoGoal>)))
  "Returns md5sum for a message object of type '<MakePhotoGoal>"
  "00b32418588cddf81e8ce2583c63f170")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MakePhotoGoal)))
  "Returns md5sum for a message object of type 'MakePhotoGoal"
  "00b32418588cddf81e8ce2583c63f170")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MakePhotoGoal>)))
  "Returns full string definition for message of type '<MakePhotoGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%MakePhoto make_photo_command~%~%================================================================================~%MSG: coffebot/MakePhoto~%#message for command to make photo~%~%bool make_photo~%string photo_file_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MakePhotoGoal)))
  "Returns full string definition for message of type 'MakePhotoGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%MakePhoto make_photo_command~%~%================================================================================~%MSG: coffebot/MakePhoto~%#message for command to make photo~%~%bool make_photo~%string photo_file_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MakePhotoGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'make_photo_command))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MakePhotoGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MakePhotoGoal
    (cl:cons ':make_photo_command (make_photo_command msg))
))
