; Auto-generated. Do not edit!


(cl:in-package coffebot-msg)


;//! \htmlinclude MakePhotoActionGoal.msg.html

(cl:defclass <MakePhotoActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type coffebot-msg:MakePhotoGoal
    :initform (cl:make-instance 'coffebot-msg:MakePhotoGoal)))
)

(cl:defclass MakePhotoActionGoal (<MakePhotoActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MakePhotoActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MakePhotoActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name coffebot-msg:<MakePhotoActionGoal> is deprecated: use coffebot-msg:MakePhotoActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <MakePhotoActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader coffebot-msg:header-val is deprecated.  Use coffebot-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <MakePhotoActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader coffebot-msg:goal_id-val is deprecated.  Use coffebot-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <MakePhotoActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader coffebot-msg:goal-val is deprecated.  Use coffebot-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MakePhotoActionGoal>) ostream)
  "Serializes a message object of type '<MakePhotoActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MakePhotoActionGoal>) istream)
  "Deserializes a message object of type '<MakePhotoActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MakePhotoActionGoal>)))
  "Returns string type for a message object of type '<MakePhotoActionGoal>"
  "coffebot/MakePhotoActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MakePhotoActionGoal)))
  "Returns string type for a message object of type 'MakePhotoActionGoal"
  "coffebot/MakePhotoActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MakePhotoActionGoal>)))
  "Returns md5sum for a message object of type '<MakePhotoActionGoal>"
  "84716fb0286c994c7895fb0aac74e69d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MakePhotoActionGoal)))
  "Returns md5sum for a message object of type 'MakePhotoActionGoal"
  "84716fb0286c994c7895fb0aac74e69d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MakePhotoActionGoal>)))
  "Returns full string definition for message of type '<MakePhotoActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%MakePhotoGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: coffebot/MakePhotoGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%MakePhoto make_photo_command~%~%================================================================================~%MSG: coffebot/MakePhoto~%#message for command to make photo~%~%bool make_photo~%string photo_file_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MakePhotoActionGoal)))
  "Returns full string definition for message of type 'MakePhotoActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%MakePhotoGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: coffebot/MakePhotoGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%MakePhoto make_photo_command~%~%================================================================================~%MSG: coffebot/MakePhoto~%#message for command to make photo~%~%bool make_photo~%string photo_file_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MakePhotoActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MakePhotoActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MakePhotoActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
