; Auto-generated. Do not edit!


(cl:in-package coffebot-msg)


;//! \htmlinclude MakePhotoFeedback.msg.html

(cl:defclass <MakePhotoFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MakePhotoFeedback (<MakePhotoFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MakePhotoFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MakePhotoFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name coffebot-msg:<MakePhotoFeedback> is deprecated: use coffebot-msg:MakePhotoFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MakePhotoFeedback>) ostream)
  "Serializes a message object of type '<MakePhotoFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MakePhotoFeedback>) istream)
  "Deserializes a message object of type '<MakePhotoFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MakePhotoFeedback>)))
  "Returns string type for a message object of type '<MakePhotoFeedback>"
  "coffebot/MakePhotoFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MakePhotoFeedback)))
  "Returns string type for a message object of type 'MakePhotoFeedback"
  "coffebot/MakePhotoFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MakePhotoFeedback>)))
  "Returns md5sum for a message object of type '<MakePhotoFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MakePhotoFeedback)))
  "Returns md5sum for a message object of type 'MakePhotoFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MakePhotoFeedback>)))
  "Returns full string definition for message of type '<MakePhotoFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MakePhotoFeedback)))
  "Returns full string definition for message of type 'MakePhotoFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MakePhotoFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MakePhotoFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MakePhotoFeedback
))
