; Auto-generated. Do not edit!


(cl:in-package coffebot-msg)


;//! \htmlinclude MakeVideoFeedback.msg.html

(cl:defclass <MakeVideoFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MakeVideoFeedback (<MakeVideoFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MakeVideoFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MakeVideoFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name coffebot-msg:<MakeVideoFeedback> is deprecated: use coffebot-msg:MakeVideoFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MakeVideoFeedback>) ostream)
  "Serializes a message object of type '<MakeVideoFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MakeVideoFeedback>) istream)
  "Deserializes a message object of type '<MakeVideoFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MakeVideoFeedback>)))
  "Returns string type for a message object of type '<MakeVideoFeedback>"
  "coffebot/MakeVideoFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MakeVideoFeedback)))
  "Returns string type for a message object of type 'MakeVideoFeedback"
  "coffebot/MakeVideoFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MakeVideoFeedback>)))
  "Returns md5sum for a message object of type '<MakeVideoFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MakeVideoFeedback)))
  "Returns md5sum for a message object of type 'MakeVideoFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MakeVideoFeedback>)))
  "Returns full string definition for message of type '<MakeVideoFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MakeVideoFeedback)))
  "Returns full string definition for message of type 'MakeVideoFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MakeVideoFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MakeVideoFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MakeVideoFeedback
))
