// Auto-generated. Do not edit!

// (in-package coffebot.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let MakeVideo = require('./MakeVideo.js');

//-----------------------------------------------------------

class MakeVideoGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.make_photo_command = null;
    }
    else {
      if (initObj.hasOwnProperty('make_photo_command')) {
        this.make_photo_command = initObj.make_photo_command
      }
      else {
        this.make_photo_command = new MakeVideo();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MakeVideoGoal
    // Serialize message field [make_photo_command]
    bufferOffset = MakeVideo.serialize(obj.make_photo_command, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MakeVideoGoal
    let len;
    let data = new MakeVideoGoal(null);
    // Deserialize message field [make_photo_command]
    data.make_photo_command = MakeVideo.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += MakeVideo.getMessageSize(object.make_photo_command);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'coffebot/MakeVideoGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '6e36709e19038e609a732049e64a6b96';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    MakeVideo make_photo_command
    
    ================================================================================
    MSG: coffebot/MakeVideo
    #message for command to make video
    
    bool start_video
    int8 duration #duration in seconds
    string video_file_name
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MakeVideoGoal(null);
    if (msg.make_photo_command !== undefined) {
      resolved.make_photo_command = MakeVideo.Resolve(msg.make_photo_command)
    }
    else {
      resolved.make_photo_command = new MakeVideo()
    }

    return resolved;
    }
};

module.exports = MakeVideoGoal;
